/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 door.gltf
Author: Arnau Rocher Alcayde (https://sketchfab.com/ArnauRocherAlcayde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-d6b9b84b78ae4462a6cf021b412085fe
Title: Door
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Door(props) {
  const { nodes, materials } = useGLTF('/door.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Door_MAT_Door_0.geometry} material={materials.MAT_Door} />
        <mesh geometry={nodes.Parte_Pomo_MAT_Door_Handle_0.geometry} material={materials.MAT_Door_Handle} />
        <mesh geometry={nodes.Prame1_MAT_Prame_0.geometry} material={materials.MAT_Prame} />
        <mesh geometry={nodes.Maneta_2_MAT_Door_Handle_0.geometry} material={materials.MAT_Door_Handle} />
        <mesh geometry={nodes.Marco_Pomo_MAT_Door_Handle_0.geometry} material={materials.MAT_Door_Handle} />
        <mesh geometry={nodes.Maneta_1_MAT_Door_Handle_0.geometry} material={materials.MAT_Door_Handle} />
      </group>
    </group>
  )
}

useGLTF.preload('/door.gltf')
