/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 palmera.gltf
Author: Maru (https://sketchfab.com/marutho97)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/palmera-lowpoly-palm-tree-1df51470fb9e4f4191d9337ba80ee10f
Title: Palmera Lowpoly (Palm Tree)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Palmera(props) {
  const { nodes, materials } = useGLTF('/palmera.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.aiStandardSurface1SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.aiStandardSurface2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.aiStandardSurface3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/palmera.gltf')
