/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.gltf
Author: Vincent (https://sketchfab.com/vboichut)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/investigator-office-4fc1bfb9861e473488f99192525c0396
Title: Investigator Office
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Room(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/room.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="ad90d894e0be4b3cb781258dca15e277fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="polySurface225" position={[60.21, 222.66, -428.71]} rotation={[-1.68, -0.31, 0.3]}>
                  <mesh name="polySurface225_officelambert44SG1_0" geometry={nodes.polySurface225_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                </group>
                <group name="officepolySurface1">
                  <group name="polySurface1">
                    <mesh name="polySurface1_Default_Material_0" geometry={nodes.polySurface1_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="polySurface2">
                    <mesh name="polySurface2_Default_Material_0" geometry={nodes.polySurface2_Default_Material_0.geometry} material={materials.Default_Material} />
                  </group>
                  <group name="polySurface3">
                    <mesh name="polySurface3_lambert9_0" geometry={nodes.polySurface3_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface4">
                    <mesh name="polySurface4_lambert9_0" geometry={nodes.polySurface4_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface5">
                    <mesh name="polySurface5_lambert9_0" geometry={nodes.polySurface5_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface6">
                    <mesh name="polySurface6_lambert9_0" geometry={nodes.polySurface6_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface7">
                    <mesh name="polySurface7_lambert9_0" geometry={nodes.polySurface7_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface8">
                    <mesh name="polySurface8_lambert9_0" geometry={nodes.polySurface8_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface9">
                    <mesh name="polySurface9_lambert9_0" geometry={nodes.polySurface9_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface10">
                    <mesh name="polySurface10_lambert9_0" geometry={nodes.polySurface10_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface11">
                    <mesh name="polySurface11_lambert9_0" geometry={nodes.polySurface11_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface12">
                    <mesh name="polySurface12_lambert9_0" geometry={nodes.polySurface12_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface13">
                    <mesh name="polySurface13_lambert9_0" geometry={nodes.polySurface13_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface14">
                    <mesh name="polySurface14_lambert9_0" geometry={nodes.polySurface14_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface15">
                    <mesh name="polySurface15_lambert9_0" geometry={nodes.polySurface15_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface16">
                    <mesh name="polySurface16_lambert9_0" geometry={nodes.polySurface16_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface17">
                    <mesh name="polySurface17_lambert9_0" geometry={nodes.polySurface17_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface18">
                    <mesh name="polySurface18_lambert9_0" geometry={nodes.polySurface18_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface19">
                    <mesh name="polySurface19_lambert9_0" geometry={nodes.polySurface19_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface20">
                    <mesh name="polySurface20_lambert9_0" geometry={nodes.polySurface20_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface21">
                    <mesh name="polySurface21_lambert9_0" geometry={nodes.polySurface21_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface22">
                    <mesh name="polySurface22_lambert9_0" geometry={nodes.polySurface22_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface23">
                    <mesh name="polySurface23_lambert9_0" geometry={nodes.polySurface23_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface24">
                    <mesh name="polySurface24_lambert9_0" geometry={nodes.polySurface24_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface25">
                    <mesh name="polySurface25_lambert9_0" geometry={nodes.polySurface25_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface26">
                    <mesh name="polySurface26_lambert9_0" geometry={nodes.polySurface26_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface27">
                    <mesh name="polySurface27_lambert9_0" geometry={nodes.polySurface27_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface28">
                    <mesh name="polySurface28_lambert9_0" geometry={nodes.polySurface28_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface29">
                    <mesh name="polySurface29_lambert9_0" geometry={nodes.polySurface29_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface30">
                    <mesh name="polySurface30_lambert9_0" geometry={nodes.polySurface30_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface31">
                    <mesh name="polySurface31_lambert9_0" geometry={nodes.polySurface31_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface32">
                    <mesh name="polySurface32_lambert9_0" geometry={nodes.polySurface32_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface33">
                    <mesh name="polySurface33_lambert9_0" geometry={nodes.polySurface33_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface34">
                    <mesh name="polySurface34_lambert9_0" geometry={nodes.polySurface34_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface35">
                    <mesh name="polySurface35_lambert9_0" geometry={nodes.polySurface35_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface36">
                    <mesh name="polySurface36_lambert9_0" geometry={nodes.polySurface36_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface37">
                    <mesh name="polySurface37_lambert9_0" geometry={nodes.polySurface37_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface38">
                    <mesh name="polySurface38_lambert9_0" geometry={nodes.polySurface38_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface39">
                    <mesh name="polySurface39_lambert9_0" geometry={nodes.polySurface39_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface40">
                    <mesh name="polySurface40_lambert9_0" geometry={nodes.polySurface40_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface41">
                    <mesh name="polySurface41_lambert9_0" geometry={nodes.polySurface41_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface42">
                    <mesh name="polySurface42_lambert9_0" geometry={nodes.polySurface42_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface43">
                    <mesh name="polySurface43_lambert9_0" geometry={nodes.polySurface43_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface44">
                    <mesh name="polySurface44_lambert9_0" geometry={nodes.polySurface44_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface45">
                    <mesh name="polySurface45_lambert9_0" geometry={nodes.polySurface45_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface46">
                    <mesh name="polySurface46_lambert9_0" geometry={nodes.polySurface46_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface47">
                    <mesh name="polySurface47_lambert9_0" geometry={nodes.polySurface47_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface48">
                    <mesh name="polySurface48_lambert9_0" geometry={nodes.polySurface48_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface49">
                    <mesh name="polySurface49_lambert9_0" geometry={nodes.polySurface49_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface50">
                    <mesh name="polySurface50_lambert9_0" geometry={nodes.polySurface50_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface51">
                    <mesh name="polySurface51_lambert9_0" geometry={nodes.polySurface51_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface52">
                    <mesh name="polySurface52_lambert9_0" geometry={nodes.polySurface52_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface53">
                    <mesh name="polySurface53_lambert9_0" geometry={nodes.polySurface53_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface54">
                    <mesh name="polySurface54_lambert9_0" geometry={nodes.polySurface54_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface55">
                    <mesh name="polySurface55_officelambert17SG1_0" geometry={nodes.polySurface55_officelambert17SG1_0.geometry} material={materials.officelambert17SG1} />
                  </group>
                  <group name="polySurface56">
                    <mesh name="polySurface56_officelambert17SG1_0" geometry={nodes.polySurface56_officelambert17SG1_0.geometry} material={materials.officelambert17SG1} />
                  </group>
                  <group name="polySurface57">
                    <mesh name="polySurface57_officelambert17SG1_0" geometry={nodes.polySurface57_officelambert17SG1_0.geometry} material={materials.officelambert17SG1} />
                  </group>
                  <group name="polySurface58">
                    <mesh name="polySurface58_officelambert17SG1_0" geometry={nodes.polySurface58_officelambert17SG1_0.geometry} material={materials.officelambert17SG1} />
                  </group>
                  <group name="polySurface59">
                    <mesh name="polySurface59_officelambert17SG1_0" geometry={nodes.polySurface59_officelambert17SG1_0.geometry} material={materials.officelambert17SG1} />
                  </group>
                  <group name="polySurface60">
                    <mesh name="polySurface60_officelambert17SG1_0" geometry={nodes.polySurface60_officelambert17SG1_0.geometry} material={materials.officelambert17SG1} />
                  </group>
                  <group name="polySurface61">
                    <mesh name="polySurface61_lambert5_0" geometry={nodes.polySurface61_lambert5_0.geometry} material={materials.lambert5} />
                  </group>
                  <group name="polySurface62">
                    <mesh name="polySurface62_lambert3_0" geometry={nodes.polySurface62_lambert3_0.geometry} material={materials.lambert3} />
                  </group>
                  <group name="polySurface63">
                    <mesh name="polySurface63_lambert4_0" geometry={nodes.polySurface63_lambert4_0.geometry} material={materials.lambert4} />
                  </group>
                  <group name="polySurface64">
                    <mesh name="polySurface64_lambert8_0" geometry={nodes.polySurface64_lambert8_0.geometry} material={materials.lambert8} />
                  </group>
                  <group name="polySurface65">
                    <mesh name="polySurface65_lambert8_0" geometry={nodes.polySurface65_lambert8_0.geometry} material={materials.lambert8} />
                  </group>
                  <group name="polySurface66">
                    <mesh name="polySurface66_lambert5_0" geometry={nodes.polySurface66_lambert5_0.geometry} material={materials.lambert5} />
                  </group>
                  <group name="polySurface67">
                    <mesh name="polySurface67_lambert3_0" geometry={nodes.polySurface67_lambert3_0.geometry} material={materials.lambert3} />
                  </group>
                  <group name="polySurface68">
                    <mesh name="polySurface68_lambert4_0" geometry={nodes.polySurface68_lambert4_0.geometry} material={materials.lambert4} />
                  </group>
                  <group name="polySurface69">
                    <mesh name="polySurface69_officelambert36SG1_0" geometry={nodes.polySurface69_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface70">
                    <mesh name="polySurface70_officelambert36SG1_0" geometry={nodes.polySurface70_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface71">
                    <mesh name="polySurface71_officelambert36SG1_0" geometry={nodes.polySurface71_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface72">
                    <mesh name="polySurface72_officelambert36SG1_0" geometry={nodes.polySurface72_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface73">
                    <mesh name="polySurface73_officelambert36SG1_0" geometry={nodes.polySurface73_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface74">
                    <mesh name="polySurface74_officelambert36SG1_0" geometry={nodes.polySurface74_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface75">
                    <mesh name="polySurface75_officelambert36SG1_0" geometry={nodes.polySurface75_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface76">
                    <mesh name="polySurface76_officelambert36SG1_0" geometry={nodes.polySurface76_officelambert36SG1_0.geometry} material={materials.officelambert36SG1} />
                  </group>
                  <group name="polySurface77">
                    <mesh name="polySurface77_lambert2_0" geometry={nodes.polySurface77_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface78">
                    <mesh name="polySurface78_officelambert42SG1_0" geometry={nodes.polySurface78_officelambert42SG1_0.geometry} material={materials.officelambert42SG1} />
                  </group>
                  <group name="polySurface79">
                    <mesh name="polySurface79_lambert2_0" geometry={nodes.polySurface79_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface80">
                    <mesh name="polySurface80_lambert2_0" geometry={nodes.polySurface80_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface81">
                    <mesh name="polySurface81_officelambert42SG1_0" geometry={nodes.polySurface81_officelambert42SG1_0.geometry} material={materials.officelambert42SG1} />
                  </group>
                  <group name="polySurface82">
                    <mesh name="polySurface82_officelambert42SG1_0" geometry={nodes.polySurface82_officelambert42SG1_0.geometry} material={materials.officelambert42SG1} />
                  </group>
                  <group name="polySurface83">
                    <mesh name="polySurface83_officelambert42SG1_0" geometry={nodes.polySurface83_officelambert42SG1_0.geometry} material={materials.officelambert42SG1} />
                  </group>
                  <group name="polySurface84">
                    <mesh name="polySurface84_lambert2_0" geometry={nodes.polySurface84_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface85">
                    <mesh name="polySurface85_lambert2_0" geometry={nodes.polySurface85_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface86">
                    <mesh name="polySurface86_lambert2_0" geometry={nodes.polySurface86_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface87">
                    <mesh name="polySurface87_officelambert37SG1_0" geometry={nodes.polySurface87_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface88">
                    <mesh name="polySurface88_officelambert37SG1_0" geometry={nodes.polySurface88_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface89">
                    <mesh name="polySurface89_officelambert37SG1_0" geometry={nodes.polySurface89_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface90">
                    <mesh name="polySurface90_officelambert37SG1_0" geometry={nodes.polySurface90_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface91">
                    <mesh name="polySurface91_officelambert37SG1_0" geometry={nodes.polySurface91_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface92">
                    <mesh name="polySurface92_officelambert37SG1_0" geometry={nodes.polySurface92_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface93">
                    <mesh name="polySurface93_officelambert37SG1_0" geometry={nodes.polySurface93_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface94">
                    <mesh name="polySurface94_officelambert37SG1_0" geometry={nodes.polySurface94_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface95">
                    <mesh name="polySurface95_officelambert35SG1_0" geometry={nodes.polySurface95_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface96">
                    <mesh name="polySurface96_officelambert35SG1_0" geometry={nodes.polySurface96_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface97">
                    <mesh name="polySurface97_officelambert35SG1_0" geometry={nodes.polySurface97_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface98">
                    <mesh name="polySurface98_officelambert35SG1_0" geometry={nodes.polySurface98_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface99">
                    <mesh name="polySurface99_officelambert35SG1_0" geometry={nodes.polySurface99_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface100">
                    <mesh name="polySurface100_officelambert35SG1_0" geometry={nodes.polySurface100_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface101">
                    <mesh name="polySurface101_officelambert35SG1_0" geometry={nodes.polySurface101_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface102">
                    <mesh name="polySurface102_officelambert35SG1_0" geometry={nodes.polySurface102_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface103">
                    <mesh name="polySurface103_officelambert35SG1_0" geometry={nodes.polySurface103_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface104">
                    <mesh name="polySurface104_officelambert35SG1_0" geometry={nodes.polySurface104_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface105">
                    <mesh name="polySurface105_officelambert35SG1_0" geometry={nodes.polySurface105_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface106">
                    <mesh name="polySurface106_officelambert35SG1_0" geometry={nodes.polySurface106_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface107">
                    <mesh name="polySurface107_officelambert35SG1_0" geometry={nodes.polySurface107_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface108">
                    <mesh name="polySurface108_officelambert35SG1_0" geometry={nodes.polySurface108_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface109">
                    <mesh name="polySurface109_officelambert35SG1_0" geometry={nodes.polySurface109_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface110">
                    <mesh name="polySurface110_lambert2_0" geometry={nodes.polySurface110_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface111">
                    <mesh name="polySurface111_officelambert35SG1_0" geometry={nodes.polySurface111_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface112">
                    <mesh name="polySurface112_officelambert35SG1_0" geometry={nodes.polySurface112_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface113">
                    <mesh name="polySurface113_officelambert35SG1_0" geometry={nodes.polySurface113_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface114">
                    <mesh name="polySurface114_lambert2_0" geometry={nodes.polySurface114_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface115">
                    <mesh name="polySurface115_officelambert35SG1_0" geometry={nodes.polySurface115_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface116">
                    <mesh name="polySurface116_officelambert35SG1_0" geometry={nodes.polySurface116_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface117">
                    <mesh name="polySurface117_officelambert35SG1_0" geometry={nodes.polySurface117_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface118">
                    <mesh name="polySurface118_lambert2_0" geometry={nodes.polySurface118_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface119">
                    <mesh name="polySurface119_officelambert35SG1_0" geometry={nodes.polySurface119_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface120">
                    <mesh name="polySurface120_officelambert35SG1_0" geometry={nodes.polySurface120_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface121">
                    <mesh name="polySurface121_officelambert35SG1_0" geometry={nodes.polySurface121_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface122">
                    <mesh name="polySurface122_officelambert35SG1_0" geometry={nodes.polySurface122_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface123">
                    <mesh name="polySurface123_officelambert35SG1_0" geometry={nodes.polySurface123_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface124">
                    <mesh name="polySurface124_officelambert35SG1_0" geometry={nodes.polySurface124_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface125">
                    <mesh name="polySurface125_officelambert35SG1_0" geometry={nodes.polySurface125_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface126">
                    <mesh name="polySurface126_officelambert35SG1_0" geometry={nodes.polySurface126_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface127">
                    <mesh name="polySurface127_officelambert35SG1_0" geometry={nodes.polySurface127_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface128">
                    <mesh name="polySurface128_officelambert35SG1_0" geometry={nodes.polySurface128_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface129">
                    <mesh name="polySurface129_officelambert35SG1_0" geometry={nodes.polySurface129_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface130">
                    <mesh name="polySurface130_officelambert35SG1_0" geometry={nodes.polySurface130_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface131">
                    <mesh name="polySurface131_officelambert35SG1_0" geometry={nodes.polySurface131_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface132">
                    <mesh name="polySurface132_officelambert35SG1_0" geometry={nodes.polySurface132_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface133">
                    <mesh name="polySurface133_officelambert35SG1_0" geometry={nodes.polySurface133_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface134">
                    <mesh name="polySurface134_officelambert35SG1_0" geometry={nodes.polySurface134_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface135">
                    <mesh name="polySurface135_officelambert35SG1_0" geometry={nodes.polySurface135_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface136">
                    <mesh name="polySurface136_officelambert35SG1_0" geometry={nodes.polySurface136_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface137">
                    <mesh name="polySurface137_officelambert35SG1_0" geometry={nodes.polySurface137_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface138">
                    <mesh name="polySurface138_officelambert35SG1_0" geometry={nodes.polySurface138_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface139">
                    <mesh name="polySurface139_officelambert35SG1_0" geometry={nodes.polySurface139_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface140">
                    <mesh name="polySurface140_officelambert35SG1_0" geometry={nodes.polySurface140_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface141">
                    <mesh name="polySurface141_officelambert35SG1_0" geometry={nodes.polySurface141_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface142">
                    <mesh name="polySurface142_officelambert35SG1_0" geometry={nodes.polySurface142_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface143">
                    <mesh name="polySurface143_officelambert35SG1_0" geometry={nodes.polySurface143_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface144">
                    <mesh name="polySurface144_officelambert35SG1_0" geometry={nodes.polySurface144_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface145">
                    <mesh name="polySurface145_officelambert35SG1_0" geometry={nodes.polySurface145_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface146">
                    <mesh name="polySurface146_officelambert35SG1_0" geometry={nodes.polySurface146_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface147">
                    <mesh name="polySurface147_officelambert35SG1_0" geometry={nodes.polySurface147_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface148">
                    <mesh name="polySurface148_officelambert35SG1_0" geometry={nodes.polySurface148_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface149">
                    <mesh name="polySurface149_officelambert35SG1_0" geometry={nodes.polySurface149_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface150">
                    <mesh name="polySurface150_officelambert35SG1_0" geometry={nodes.polySurface150_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface151">
                    <mesh name="polySurface151_officelambert35SG1_0" geometry={nodes.polySurface151_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface152">
                    <mesh name="polySurface152_officelambert35SG1_0" geometry={nodes.polySurface152_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface153">
                    <mesh name="polySurface153_officelambert35SG1_0" geometry={nodes.polySurface153_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface154">
                    <mesh name="polySurface154_officelambert35SG1_0" geometry={nodes.polySurface154_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface155">
                    <mesh name="polySurface155_officelambert35SG1_0" geometry={nodes.polySurface155_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface156">
                    <mesh name="polySurface156_officelambert35SG1_0" geometry={nodes.polySurface156_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface157">
                    <mesh name="polySurface157_officelambert35SG1_0" geometry={nodes.polySurface157_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface158">
                    <mesh name="polySurface158_officelambert35SG1_0" geometry={nodes.polySurface158_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface159">
                    <mesh name="polySurface159_officelambert35SG1_0" geometry={nodes.polySurface159_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface160">
                    <mesh name="polySurface160_officelambert35SG1_0" geometry={nodes.polySurface160_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface161">
                    <mesh name="polySurface161_officelambert35SG1_0" geometry={nodes.polySurface161_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface162">
                    <mesh name="polySurface162_officelambert35SG1_0" geometry={nodes.polySurface162_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface163">
                    <mesh name="polySurface163_officelambert35SG1_0" geometry={nodes.polySurface163_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface164">
                    <mesh name="polySurface164_lambert2_0" geometry={nodes.polySurface164_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface165">
                    <mesh name="polySurface165_officelambert35SG1_0" geometry={nodes.polySurface165_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface166">
                    <mesh name="polySurface166_officelambert35SG1_0" geometry={nodes.polySurface166_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface167">
                    <mesh name="polySurface167_officelambert35SG1_0" geometry={nodes.polySurface167_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface168">
                    <mesh name="polySurface168_officelambert35SG1_0" geometry={nodes.polySurface168_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface169">
                    <mesh name="polySurface169_officelambert35SG1_0" geometry={nodes.polySurface169_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface170">
                    <mesh name="polySurface170_officelambert35SG1_0" geometry={nodes.polySurface170_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface171">
                    <mesh name="polySurface171_officelambert35SG1_0" geometry={nodes.polySurface171_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface172">
                    <mesh name="polySurface172_lambert2_0" geometry={nodes.polySurface172_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface173">
                    <mesh name="polySurface173_officelambert35SG1_0" geometry={nodes.polySurface173_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface174">
                    <mesh name="polySurface174_officelambert35SG1_0" geometry={nodes.polySurface174_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface175">
                    <mesh name="polySurface175_officelambert35SG1_0" geometry={nodes.polySurface175_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface176">
                    <mesh name="polySurface176_lambert2_0" geometry={nodes.polySurface176_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface177">
                    <mesh name="polySurface177_officelambert35SG1_0" geometry={nodes.polySurface177_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface178">
                    <mesh name="polySurface178_officelambert35SG1_0" geometry={nodes.polySurface178_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface179">
                    <mesh name="polySurface179_lambert2_0" geometry={nodes.polySurface179_lambert2_0.geometry} material={materials.lambert2} />
                  </group>
                  <group name="polySurface180">
                    <mesh name="polySurface180_officelambert35SG1_0" geometry={nodes.polySurface180_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface181">
                    <mesh name="polySurface181_officelambert35SG1_0" geometry={nodes.polySurface181_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface182">
                    <mesh name="polySurface182_officelambert35SG1_0" geometry={nodes.polySurface182_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface183">
                    <mesh name="polySurface183_officelambert35SG1_0" geometry={nodes.polySurface183_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface184">
                    <mesh name="polySurface184_officelambert35SG1_0" geometry={nodes.polySurface184_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface185">
                    <mesh name="polySurface185_officelambert35SG1_0" geometry={nodes.polySurface185_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface186">
                    <mesh name="polySurface186_officelambert35SG1_0" geometry={nodes.polySurface186_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface187">
                    <mesh name="polySurface187_officelambert35SG1_0" geometry={nodes.polySurface187_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface188">
                    <mesh name="polySurface188_officelambert35SG1_0" geometry={nodes.polySurface188_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface189">
                    <mesh name="polySurface189_officelambert35SG1_0" geometry={nodes.polySurface189_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface190">
                    <mesh name="polySurface190_officelambert35SG1_0" geometry={nodes.polySurface190_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface191">
                    <mesh name="polySurface191_officelambert35SG1_0" geometry={nodes.polySurface191_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface192">
                    <mesh name="polySurface192_officelambert35SG1_0" geometry={nodes.polySurface192_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface193">
                    <mesh name="polySurface193_officelambert35SG1_0" geometry={nodes.polySurface193_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface194">
                    <mesh name="polySurface194_officelambert35SG1_0" geometry={nodes.polySurface194_officelambert35SG1_0.geometry} material={materials.officelambert35SG1} />
                  </group>
                  <group name="polySurface195">
                    <mesh name="polySurface195_officelambert37SG1_0" geometry={nodes.polySurface195_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface196">
                    <mesh name="polySurface196_officelambert37SG1_0" geometry={nodes.polySurface196_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface197">
                    <mesh name="polySurface197_officelambert44SG1_0" geometry={nodes.polySurface197_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface198">
                    <mesh name="polySurface198_officelambert44SG1_0" geometry={nodes.polySurface198_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface199">
                    <mesh name="polySurface199_officelambert44SG1_0" geometry={nodes.polySurface199_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface200">
                    <mesh name="polySurface200_officelambert44SG1_0" geometry={nodes.polySurface200_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface201">
                    <mesh name="polySurface201_officelambert44SG1_0" geometry={nodes.polySurface201_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface202">
                    <mesh name="polySurface202_officelambert44SG1_0" geometry={nodes.polySurface202_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface203">
                    <mesh name="polySurface203_officelambert44SG1_0" geometry={nodes.polySurface203_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface204">
                    <mesh name="polySurface204_officelambert44SG1_0" geometry={nodes.polySurface204_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface205">
                    <mesh name="polySurface205_officelambert44SG1_0" geometry={nodes.polySurface205_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface206">
                    <mesh name="polySurface206_officelambert44SG1_0" geometry={nodes.polySurface206_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface207">
                    <mesh name="polySurface207_officelambert44SG1_0" geometry={nodes.polySurface207_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface208">
                    <mesh name="polySurface208_officelambert44SG1_0" geometry={nodes.polySurface208_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface209">
                    <mesh name="polySurface209_officelambert44SG1_0" geometry={nodes.polySurface209_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface210">
                    <mesh name="polySurface210_officelambert44SG1_0" geometry={nodes.polySurface210_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface211">
                    <mesh name="polySurface211_officelambert44SG1_0" geometry={nodes.polySurface211_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface212">
                    <mesh name="polySurface212_officelambert44SG1_0" geometry={nodes.polySurface212_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface213">
                    <mesh name="polySurface213_officelambert44SG1_0" geometry={nodes.polySurface213_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface214">
                    <mesh name="polySurface214_officelambert44SG1_0" geometry={nodes.polySurface214_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface215">
                    <mesh name="polySurface215_officelambert44SG1_0" geometry={nodes.polySurface215_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface216">
                    <mesh name="polySurface216_officelambert44SG1_0" geometry={nodes.polySurface216_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface217">
                    <mesh name="polySurface217_officelambert44SG1_0" geometry={nodes.polySurface217_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface218">
                    <mesh name="polySurface218_officelambert44SG1_0" geometry={nodes.polySurface218_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface219">
                    <mesh name="polySurface219_officelambert44SG1_0" geometry={nodes.polySurface219_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface220">
                    <mesh name="polySurface220_officelambert44SG1_0" geometry={nodes.polySurface220_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface221">
                    <mesh name="polySurface221_officelambert44SG1_0" geometry={nodes.polySurface221_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface226">
                    <mesh name="polySurface226_officelambert44SG1_0" geometry={nodes.polySurface226_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface227">
                    <mesh name="polySurface227_officelambert44SG1_0" geometry={nodes.polySurface227_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface228">
                    <mesh name="polySurface228_officelambert44SG1_0" geometry={nodes.polySurface228_officelambert44SG1_0.geometry} material={materials.officelambert44SG1} />
                  </group>
                  <group name="polySurface229">
                    <mesh name="polySurface229_officelambert20SG1_0" geometry={nodes.polySurface229_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface230">
                    <mesh name="polySurface230_officelambert20SG1_0" geometry={nodes.polySurface230_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface231">
                    <mesh name="polySurface231_officelambert20SG1_0" geometry={nodes.polySurface231_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface232">
                    <mesh name="polySurface232_officelambert20SG1_0" geometry={nodes.polySurface232_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface233">
                    <mesh name="polySurface233_officelambert20SG1_0" geometry={nodes.polySurface233_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface234">
                    <mesh name="polySurface234_officelambert20SG1_0" geometry={nodes.polySurface234_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface235">
                    <mesh name="polySurface235_officelambert20SG1_0" geometry={nodes.polySurface235_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface236">
                    <mesh name="polySurface236_officelambert20SG1_0" geometry={nodes.polySurface236_officelambert20SG1_0.geometry} material={materials.officelambert20SG1} />
                  </group>
                  <group name="polySurface237">
                    <mesh name="polySurface237_officelambert13SG1_0" geometry={nodes.polySurface237_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface238">
                    <mesh name="polySurface238_lambert9_0" geometry={nodes.polySurface238_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface239">
                    <mesh name="polySurface239_officelambert13SG1_0" geometry={nodes.polySurface239_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface240">
                    <mesh name="polySurface240_officelambert13SG1_0" geometry={nodes.polySurface240_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface241">
                    <mesh name="polySurface241_officelambert13SG1_0" geometry={nodes.polySurface241_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface242">
                    <mesh name="polySurface242_officelambert13SG1_0" geometry={nodes.polySurface242_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface243">
                    <mesh name="polySurface243_officelambert13SG1_0" geometry={nodes.polySurface243_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface244">
                    <mesh name="polySurface244_officelambert13SG1_0" geometry={nodes.polySurface244_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface245">
                    <mesh name="polySurface245_officelambert13SG1_0" geometry={nodes.polySurface245_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface246">
                    <mesh name="polySurface246_officelambert13SG1_0" geometry={nodes.polySurface246_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface247">
                    <mesh name="polySurface247_officelambert13SG1_0" geometry={nodes.polySurface247_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface248">
                    <mesh name="polySurface248_officelambert13SG1_0" geometry={nodes.polySurface248_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface249">
                    <mesh name="polySurface249_officelambert13SG1_0" geometry={nodes.polySurface249_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface250">
                    <mesh name="polySurface250_officelambert13SG1_0" geometry={nodes.polySurface250_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface251">
                    <mesh name="polySurface251_officelambert13SG1_0" geometry={nodes.polySurface251_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface252">
                    <mesh name="polySurface252_officelambert13SG1_0" geometry={nodes.polySurface252_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface253">
                    <mesh name="polySurface253_officelambert13SG1_0" geometry={nodes.polySurface253_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface254">
                    <mesh name="polySurface254_officelambert13SG1_0" geometry={nodes.polySurface254_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface255">
                    <mesh name="polySurface255_officelambert13SG1_0" geometry={nodes.polySurface255_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface256">
                    <mesh name="polySurface256_officelambert13SG1_0" geometry={nodes.polySurface256_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface257">
                    <mesh name="polySurface257_officelambert13SG1_0" geometry={nodes.polySurface257_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface258">
                    <mesh name="polySurface258_officelambert13SG1_0" geometry={nodes.polySurface258_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface259">
                    <mesh name="polySurface259_officelambert13SG1_0" geometry={nodes.polySurface259_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface260">
                    <mesh name="polySurface260_officelambert13SG1_0" geometry={nodes.polySurface260_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface261">
                    <mesh name="polySurface261_officelambert13SG1_0" geometry={nodes.polySurface261_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface262">
                    <mesh name="polySurface262_officelambert13SG1_0" geometry={nodes.polySurface262_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface263">
                    <mesh name="polySurface263_officelambert13SG1_0" geometry={nodes.polySurface263_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface264">
                    <mesh name="polySurface264_officelambert13SG1_0" geometry={nodes.polySurface264_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface265">
                    <mesh name="polySurface265_officelambert13SG1_0" geometry={nodes.polySurface265_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface266">
                    <mesh name="polySurface266_officelambert13SG1_0" geometry={nodes.polySurface266_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface267">
                    <mesh name="polySurface267_officelambert13SG1_0" geometry={nodes.polySurface267_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface268">
                    <mesh name="polySurface268_officelambert13SG1_0" geometry={nodes.polySurface268_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface269">
                    <mesh name="polySurface269_officelambert13SG1_0" geometry={nodes.polySurface269_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface270">
                    <mesh name="polySurface270_officelambert13SG1_0" geometry={nodes.polySurface270_officelambert13SG1_0.geometry} material={materials.officelambert13SG1} />
                  </group>
                  <group name="polySurface271">
                    <mesh name="polySurface271_officelambert15SG1_0" geometry={nodes.polySurface271_officelambert15SG1_0.geometry} material={materials.officelambert15SG1} />
                  </group>
                  <group name="polySurface272">
                    <mesh name="polySurface272_officelambert15SG1_0" geometry={nodes.polySurface272_officelambert15SG1_0.geometry} material={materials.officelambert15SG1} />
                  </group>
                  <group name="polySurface273">
                    <mesh name="polySurface273_officelambert15SG1_0" geometry={nodes.polySurface273_officelambert15SG1_0.geometry} material={materials.officelambert15SG1} />
                  </group>
                  <group name="polySurface274">
                    <mesh name="polySurface274_officelambert15SG1_0" geometry={nodes.polySurface274_officelambert15SG1_0.geometry} material={materials.officelambert15SG1} />
                  </group>
                  <group name="polySurface275">
                    <mesh name="polySurface275_officelambert15SG1_0" geometry={nodes.polySurface275_officelambert15SG1_0.geometry} material={materials.officelambert15SG1} />
                  </group>
                  <group name="polySurface276">
                    <mesh name="polySurface276_officelambert15SG1_0" geometry={nodes.polySurface276_officelambert15SG1_0.geometry} material={materials.officelambert15SG1} />
                  </group>
                  <group name="polySurface277">
                    <mesh name="polySurface277_officelambert15SG1_0" geometry={nodes.polySurface277_officelambert15SG1_0.geometry} material={materials.officelambert15SG1} />
                  </group>
                  <group name="polySurface278">
                    <mesh name="polySurface278_lambert9_0" geometry={nodes.polySurface278_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface279">
                    <mesh name="polySurface279_lambert9_0" geometry={nodes.polySurface279_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface280">
                    <mesh name="polySurface280_lambert9_0" geometry={nodes.polySurface280_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface281">
                    <mesh name="polySurface281_lambert9_0" geometry={nodes.polySurface281_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface282">
                    <mesh name="polySurface282_lambert9_0" geometry={nodes.polySurface282_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface283">
                    <mesh name="polySurface283_lambert9_0" geometry={nodes.polySurface283_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface284">
                    <mesh name="polySurface284_lambert9_0" geometry={nodes.polySurface284_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface285">
                    <mesh name="polySurface285_lambert9_0" geometry={nodes.polySurface285_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface286">
                    <mesh name="polySurface286_lambert9_0" geometry={nodes.polySurface286_lambert9_0.geometry} material={materials.lambert9} />
                  </group>
                  <group name="polySurface287">
                    <mesh name="polySurface287_officelambert24SG1_0" geometry={nodes.polySurface287_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface288">
                    <mesh name="polySurface288_officelambert24SG1_0" geometry={nodes.polySurface288_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface289">
                    <mesh name="polySurface289_officelambert24SG1_0" geometry={nodes.polySurface289_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface290">
                    <mesh name="polySurface290_officelambert24SG1_0" geometry={nodes.polySurface290_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface291">
                    <mesh name="polySurface291_officelambert24SG1_0" geometry={nodes.polySurface291_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface292">
                    <mesh name="polySurface292_officelambert24SG1_0" geometry={nodes.polySurface292_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface293">
                    <mesh name="polySurface293_officelambert24SG1_0" geometry={nodes.polySurface293_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface294">
                    <mesh name="polySurface294_officelambert24SG1_0" geometry={nodes.polySurface294_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface295">
                    <mesh name="polySurface295_officelambert24SG1_0" geometry={nodes.polySurface295_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface296">
                    <mesh name="polySurface296_officelambert24SG1_0" geometry={nodes.polySurface296_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface297">
                    <mesh name="polySurface297_officelambert24SG1_0" geometry={nodes.polySurface297_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface298">
                    <mesh name="polySurface298_officelambert24SG1_0" geometry={nodes.polySurface298_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface299">
                    <mesh name="polySurface299_officelambert24SG1_0" geometry={nodes.polySurface299_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface300">
                    <mesh name="polySurface300_officelambert24SG1_0" geometry={nodes.polySurface300_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface301">
                    <mesh name="polySurface301_officelambert24SG1_0" geometry={nodes.polySurface301_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface302">
                    <mesh name="polySurface302_officelambert24SG1_0" geometry={nodes.polySurface302_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface303">
                    <mesh name="polySurface303_officelambert24SG1_0" geometry={nodes.polySurface303_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface304">
                    <mesh name="polySurface304_officelambert24SG1_0" geometry={nodes.polySurface304_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface305">
                    <mesh name="polySurface305_officelambert24SG1_0" geometry={nodes.polySurface305_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface306">
                    <mesh name="polySurface306_officelambert24SG1_0" geometry={nodes.polySurface306_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface307">
                    <mesh name="polySurface307_officelambert24SG1_0" geometry={nodes.polySurface307_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface308">
                    <mesh name="polySurface308_officelambert24SG1_0" geometry={nodes.polySurface308_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface309">
                    <mesh name="polySurface309_officelambert24SG1_0" geometry={nodes.polySurface309_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface310">
                    <mesh name="polySurface310_officelambert24SG1_0" geometry={nodes.polySurface310_officelambert24SG1_0.geometry} material={materials.officelambert24SG1} />
                  </group>
                  <group name="polySurface311">
                    <mesh name="polySurface311_officelambert22SG1_0" geometry={nodes.polySurface311_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                  </group>
                  <group name="polySurface312">
                    <mesh name="polySurface312_officelambert22SG1_0" geometry={nodes.polySurface312_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                  </group>
                  <group name="polySurface313">
                    <mesh name="polySurface313_officelambert22SG1_0" geometry={nodes.polySurface313_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                  </group>
                  <group name="polySurface314">
                    <mesh name="polySurface314_officelambert22SG1_0" geometry={nodes.polySurface314_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                    <mesh name="polySurface314_lambert11_0" geometry={nodes.polySurface314_lambert11_0.geometry} material={materials.lambert11} />
                  </group>
                  <group name="polySurface315">
                    <mesh name="polySurface315_officelambert22SG1_0" geometry={nodes.polySurface315_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                  </group>
                  <group name="polySurface316">
                    <mesh name="polySurface316_officelambert22SG1_0" geometry={nodes.polySurface316_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                  </group>
                  <group name="polySurface317">
                    <mesh name="polySurface317_officelambert22SG1_0" geometry={nodes.polySurface317_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                  </group>
                  <group name="polySurface318">
                    <mesh name="polySurface318_officelambert22SG1_0" geometry={nodes.polySurface318_officelambert22SG1_0.geometry} material={materials.officelambert22SG1} />
                    <mesh name="polySurface318_lambert11_0" geometry={nodes.polySurface318_lambert11_0.geometry} material={materials.lambert11} />
                  </group>
                  <group name="polySurface319">
                    <mesh name="polySurface319_officelambert21SG1_0" geometry={nodes.polySurface319_officelambert21SG1_0.geometry} material={materials.officelambert21SG1} />
                  </group>
                  <group name="polySurface320">
                    <mesh name="polySurface320_officelambert21SG1_0" geometry={nodes.polySurface320_officelambert21SG1_0.geometry} material={materials.officelambert21SG1} />
                  </group>
                  <group name="polySurface321">
                    <mesh name="polySurface321_officelambert40SG1_0" geometry={nodes.polySurface321_officelambert40SG1_0.geometry} material={materials.officelambert40SG1} />
                  </group>
                  <group name="polySurface322">
                    <mesh name="polySurface322_officelambert41SG1_0" geometry={nodes.polySurface322_officelambert41SG1_0.geometry} material={materials.officelambert41SG1} />
                  </group>
                  <group name="polySurface323">
                    <mesh name="polySurface323_officelambert21SG1_0" geometry={nodes.polySurface323_officelambert21SG1_0.geometry} material={materials.officelambert21SG1} />
                  </group>
                  <group name="polySurface462">
                    <mesh name="polySurface462_officelambert12SG1_0" geometry={nodes.polySurface462_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface463">
                    <mesh name="polySurface463_officelambert12SG1_0" geometry={nodes.polySurface463_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface464">
                    <mesh name="polySurface464_officelambert12SG1_0" geometry={nodes.polySurface464_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface465">
                    <mesh name="polySurface465_officelambert12SG1_0" geometry={nodes.polySurface465_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface466">
                    <mesh name="polySurface466_officelambert12SG1_0" geometry={nodes.polySurface466_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface467">
                    <mesh name="polySurface467_officelambert12SG1_0" geometry={nodes.polySurface467_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface468">
                    <mesh name="polySurface468_officelambert12SG1_0" geometry={nodes.polySurface468_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface469">
                    <mesh name="polySurface469_officelambert12SG1_0" geometry={nodes.polySurface469_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface470">
                    <mesh name="polySurface470_officelambert12SG1_0" geometry={nodes.polySurface470_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface471">
                    <mesh name="polySurface471_officelambert12SG1_0" geometry={nodes.polySurface471_officelambert12SG1_0.geometry} material={materials.officelambert12SG1} />
                  </group>
                  <group name="polySurface472">
                    <mesh name="polySurface472_officelambert10SG1_0" geometry={nodes.polySurface472_officelambert10SG1_0.geometry} material={materials.officelambert10SG1} />
                  </group>
                  <group name="polySurface473">
                    <mesh name="polySurface473_officelambert10SG1_0" geometry={nodes.polySurface473_officelambert10SG1_0.geometry} material={materials.officelambert10SG1} />
                  </group>
                  <group name="polySurface474">
                    <mesh name="polySurface474_officelambert19SG1_0" geometry={nodes.polySurface474_officelambert19SG1_0.geometry} material={materials.officelambert19SG1} />
                  </group>
                  <group name="polySurface475">
                    <mesh name="polySurface475_officelambert38SG1_0" geometry={nodes.polySurface475_officelambert38SG1_0.geometry} material={materials.officelambert38SG1} />
                  </group>
                  <group name="polySurface476">
                    <mesh name="polySurface476_officelambert10SG1_0" geometry={nodes.polySurface476_officelambert10SG1_0.geometry} material={materials.officelambert10SG1} />
                  </group>
                  <group name="polySurface477">
                    <mesh name="polySurface477_officelambert10SG1_0" geometry={nodes.polySurface477_officelambert10SG1_0.geometry} material={materials.officelambert10SG1} />
                  </group>
                  <group name="polySurface478">
                    <mesh name="polySurface478_officelambert27SG1_0" geometry={nodes.polySurface478_officelambert27SG1_0.geometry} material={materials.officelambert27SG1} />
                  </group>
                  <group name="polySurface479">
                    <mesh name="polySurface479_lambert7_0" geometry={nodes.polySurface479_lambert7_0.geometry} material={materials.lambert7} />
                    <mesh name="polySurface479_officelambert27SG1_0" geometry={nodes.polySurface479_officelambert27SG1_0.geometry} material={materials.officelambert27SG1} />
                    <mesh name="polySurface479_lambert6_0" geometry={nodes.polySurface479_lambert6_0.geometry} material={materials.lambert6} />
                  </group>
                  <group name="polySurface480">
                    <mesh name="polySurface480_officelambert18SG1_0" geometry={nodes.polySurface480_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface481">
                    <mesh name="polySurface481_officelambert18SG1_0" geometry={nodes.polySurface481_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface482">
                    <mesh name="polySurface482_officelambert18SG1_0" geometry={nodes.polySurface482_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface483">
                    <mesh name="polySurface483_officelambert18SG1_0" geometry={nodes.polySurface483_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface484">
                    <mesh name="polySurface484_officelambert18SG1_0" geometry={nodes.polySurface484_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface485">
                    <mesh name="polySurface485_officelambert18SG1_0" geometry={nodes.polySurface485_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface486">
                    <mesh name="polySurface486_officelambert18SG1_0" geometry={nodes.polySurface486_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface487">
                    <mesh name="polySurface487_officelambert18SG1_0" geometry={nodes.polySurface487_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface488">
                    <mesh name="polySurface488_officelambert18SG1_0" geometry={nodes.polySurface488_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface489">
                    <mesh name="polySurface489_officelambert18SG1_0" geometry={nodes.polySurface489_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface490">
                    <mesh name="polySurface490_officelambert18SG1_0" geometry={nodes.polySurface490_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface491">
                    <mesh name="polySurface491_officelambert18SG1_0" geometry={nodes.polySurface491_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface492">
                    <mesh name="polySurface492_officelambert18SG1_0" geometry={nodes.polySurface492_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface493">
                    <mesh name="polySurface493_officelambert18SG1_0" geometry={nodes.polySurface493_officelambert18SG1_0.geometry} material={materials.officelambert18SG1} />
                  </group>
                  <group name="polySurface494">
                    <mesh name="polySurface494_officelambert37SG1_0" geometry={nodes.polySurface494_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                  <group name="polySurface495">
                    <mesh name="polySurface495_officelambert37SG1_0" geometry={nodes.polySurface495_officelambert37SG1_0.geometry} material={materials.officelambert37SG1} />
                  </group>
                </group>
                <group name="pCube64">
                  <mesh name="pCube64_lambert10_0" geometry={nodes.pCube64_lambert10_0.geometry} material={materials.lambert10} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.gltf')
