/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sun.gltf
Author: IronEqual (https://sketchfab.com/ie-niels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-from-poly-by-google-67b0952528b2476c9ccd4d2daead9a3e
Title: Sun from Poly by Google
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sun(props) {
  const { nodes, materials } = useGLTF('/sun.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.lambert2SG} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/sun.gltf')
